from flask import Blueprint, request

bp = Blueprint("meta", __name__, url_prefix="/meta")

# NOTE:
# Departments list based on official OAU faculty/department listings.
# Keep this as the single source of truth for department matching.
DEPARTMENTS = sorted(set([
    "Adult Education",
    "Accounting",
    "Adult Education and Lifelong Learning",
    "Agricultural and Environmental Engineering",
    "Agricultural Economics",
    "Agricultural Extension and Rural Development",
    "Aerospace Engineering",
    "Anaesthesia",
    "Animal Science",
    "Animal Sciences",
    "Anatomy and Cell Biology",
    "Architecture",
    "Arts and Social Sciences Education",
    "Biochemistry",
    "Botany",
    "Building",
    "Business Administration",
    "Business Law",
    "Chemical Engineering",
    "Chemistry",
    "Child Dental Health",
    "Civil Engineering",
    "Clinical Pharmacy and Pharmacy Administration",
    "Community Health and Nutrition",
    "Computer Engineering",
    "Computer Science and Cyber Security",
    "Computer Science and Engineering",
    "Crop Production and Protection",
    "Demography and Social Statistics",
    "Dentistry",
    "Dermatology and Venerology",
    "Drug Research and Production Unit",
    "Dramatic Arts",
    "Economics",
    "Education and Biology",
    "Education and Chemistry",
    "Education and Economics",
    "Education and English",
    "Education and Language Arts",
    "Education and Mathematics",
    "Education and Physics",
    "Education and Political Science",
    "Education and Religious Studies",
    "Educational Foundation and Counseling",
    "Educational Management",
    "Electronic and Electrical Engineering",
    "English",
    "Estate Management",
    "Family, Nutrition and Consumer Sciences",
    "Family Nutrition and Consumer Sciences",
    "Fine and Applied Arts",
    "Food Science and Technology",
    "Foreign Languages",
    "French",
    "Geography",
    "Geology",
    "Haematology and Immunology",
    "History",
    "Human Nutrition and Dietetics",
    "Information System",
    "Institute of Education",
    "Intelligent System Engineering",
    "International Law",
    "International Relations",
    "Jurisprudence and Private Law",
    "Law",
    "Linguistics",
    "Linguistics and African Languages",
    "Local Government and Development Studies",
    "Management and Accounting",
    "Material Science and Engineering",
    "Materials Science and Engineering",
    "Mathematics",
    "Mechanical Engineering",
    "Medical Biochemistry",
    "Medical Microbiology and Parasitology",
    "Medical Pharmacology and Therapeutics",
    "Medical Rehabilitation",
    "Medicine",
    "Medicine and Surgery",
    "Mental Health",
    "Microbiology",
    "Morbid Anatomy and Forensic Medicine",
    "Music",
    "Nursing Science",
    "Nursing Sciences",
    "Obstetrics Gynaecology and Perimatology",
    "Ophthalmology",
    "Oral and Maxillofacial",
    "Orthopaedics and Traumatology",
    "Paediatrics and Child Health",
    "Pharmacognosy",
    "Pharmacology",
    "Pharmaceutics",
    "Pharmaceutical Chemistry",
    "Pharmacy",
    "Philosophy",
    "Physical and Health Education",
    "Physics",
    "Physics and Engineering Physics",
    "Physiological Sciences",
    "Plant Science",
    "Political Science",
    "Preventive and Community Dentistry",
    "Psychology",
    "Public Administration",
    "Public Law",
    "Quantity Surveying",
    "Radiology",
    "Religious Studies",
    "Restorative Dentistry",
    "Science and Technology Education",
    "Sociology and Anthropology",
    "Software Engineering",
    "Soil Science",
    "Soil Science and Land Resources Management",
    "Statistics",
    "Surveying and Geoinformatics",
    "Surgery and Oral Pathology",
    "Theatre Arts",
    "Urban and Regional Planning",
    "Zoology",
]))


@bp.get("/departments")
def get_departments():
    """
    GET /meta/departments?q=...
    - returns full list for dropdown
    - supports search using ?q=
    """
    q = (request.args.get("q") or "").strip().lower()

    if not q:
        return {"count": len(DEPARTMENTS), "departments": DEPARTMENTS}

    filtered = [d for d in DEPARTMENTS if q in d.lower()]
    return {"count": len(filtered), "departments": filtered}
